# Quick links to the docs:
# - Redwood on Render: https://render.com/docs/deploy-redwood
# - Render's Blueprint spec: https://render.com/docs/yaml-spec

services:
- name: sonastik-ee-web
  type: web
  env: static
  buildCommand: corepack enable && yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist

  envVars:
  - key: SKIP_INSTALL_DEPS
    value: true

  routes:
  - type: rewrite
    source: /.redwood/functions/*
    # Replace `destination` here after your first deploy:
    #
    # ```
    # destination: https://my-redwood-project-api.onrender.com/*
    # ```
    destination: replace_with_api_url/*
  - type: rewrite
    source: /*
    destination: /200.html

- name: sonastik-ee-api
  type: web
  plan: free
  env: node
  region: frankfurt
  buildCommand: corepack enable && yarn && yarn rw build api
  startCommand: yarn rw deploy render api

  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: sonastik-ee-db
      property: connectionString

databases:
  - name: sonastik-ee-db
    region: oregon
